run:
  timeout: 5m
issues:
  fix: true
linters-settings:
  lll:
    line-length: 200
linters:
  enable-all: true
  disable:
  - deadcode
  - execinquery
  - gomnd
  - exportloopref
  ###############
  - gochecknoglobals
  - err113
  - exhaustruct
  - mnd
  - wrapcheck
  - varnamelen
  - depguard